exports.transform = {
  _id: 'required|integer',
  name: 'string',
  business: 'integer',
  tel: 'string',
  benefit: 'string',
  detail: 'string',
  contactName: 'string',
  address: 'string',
  provinceCode: 'string|regex:/^[0-9]{2}$/',
  districtCode: 'string|regex:/^[0-9]{4}$/',
  subdistrictCode: 'string|regex:/^[0-9]{6}$/',
  englishApply: 'boolean',
  longitude: 'numeric',
  latitude: 'numeric',
  industrial: 'string',
  travelToCompany: 'string',
  logo: 'string',
  map: 'string',
  lastUpdate: 'datetime', // wait validate npm update
  lastUpdateEx: 'datetime',
  userId: 'integer',
  applyMethod: 'string',
};
