exports.transform = {
  _id: 'required|integer',
  companyId: 'required|integer',
  title: 'required|string|max:80|nothtml',
  jobType: 'string|max:25',
  subJobType: 'integer',
  contactAddress: 'string|max:255',
  contactName: 'string|max:255',
  contactTel: 'string|max:255',
  provinceCode: 'string|regex:/^[0-9]{2}$/',
  districtCode: 'string|regex:/^[0-9]{4}$/',
  subdistrictCode: 'string|regex:/^[0-9]{6}$/',
  numberOfPosition: 'string|max:100',
  salary: 'string',
  disabledPerson: 'in:0,1,2',
  marqueeUrgent: 'in:0,1,2',
  description: 'string',
  onlineStatus: 'in:0,1',
  email: 'emailjobthai',
  proxyEmail: 'string|max:255',
  isProxyEmailDisabled: 'in:0,1',
  longitude: 'numeric',
  latitude: 'numeric',
  workLocation: 'string',
  properties: 'string|max:5000',
  industrial: 'integer',
  lastupdate: 'datetime',
};
